### ISSUE TITLE
Question about linspace vector size

### ISSUE THREAD

**Issue by philw16** [uwhpsc-2016/homework3#11]
In the homework description it says that our functions will be tested using a vector size up to 1e18. However when I try to implement 1e9 or greater I recieve this error. 

```
Traceback (most recent call last):
  File "test_homework3.py", line 106, in test_chunk
    x = linspace(-1, 8, 1e9)
  File "/usr/lib/python2.7/dist-packages/numpy/core/function_base.py", line 88, in linspace
    y = _nx.arange(0, num) * step + start
MemoryError
```

Is this an error with my function or is it too difficult for a vector to be generated with that many points across such a small range?

**Comment by cswiercz** [comment]
Dang. That's interesting. I'm assuming it's an SMC issue because, although it does take a moment to execute on my personal machine, it does indeed execute.

Note that `1e9` bytes is equal to `1GB`. So `1e9` doubles is `8GB`. I just now realized that SMC does not give you that much storage...my apologies.

I will have to adjust the homework, accordingly. That's what I get for running tests on a big machine instead of SMC.

**Comment by cswiercz** [comment]
I will make an announcement and update the `README` accordingly.

**Comment by cswiercz** [comment]
My own tests show that `1e7` is near the SMC limit which is approximately `2**23`

**Comment by cswiercz** [comment]
Actually, this all makes sense now because I meant to write `2**7` and `2**18` at the end of the `README`.
